---

- yum: name={{ item }} state=present
  with_items:
    - tftp-server
    - dhcp
    - bind

- file: src=/sbin/{{ item }} dest=/usr/bin/{{ item }} state=link
  with_items:
    - in.tftpd
    - dhcpd
    - named
