sudo: false
dist: trusty

language: c

addons:
  apt:
    packages:
      - autoconf
      - bc
      - bison
      - flex
      - g++
      - gawk
      - gcc
      - gcc-multilib
      - git
      - gperf
      - libtool
      - make
      - mercurial
      - ncurses-dev
      - openssh-server
      - pv
      - subversion
      - texinfo
      - unzip
      - xz-utils


cache:
  ccache: true
  directories:
    - $HOME/.buildroot-ccache
    - $HOME/downloads
    - $HOME/go

install:
  - ./buildmistify --useartifacts --downloaddir $HOME/downloads --godir $HOME/go -- VERBOSE=0 -s source

script:
  - ./buildmistify --useartifacts --downloaddir $HOME/downloads --godir $HOME/go -- VERBOSE=0 -s

notifications:
  email: false
  slack:
    secure: "U6tm6D5myVwg3FL+zeWpfW17GrM8pVOayDYIvuagawGhKu/zftHxqwD9GQP54P1YvHSxGs0g2i7ZT4EM+EOLiHewG80Dk5Ndzrxr8Ck5mjFCxJDQkW45QaQBvY13+u9CY4i/g8LyAIOvoSxYAQS9n2dWTCgkXuSwnjUcDkaeY/Owk1qVBvu+ZeoCY02MRwUJsM5f1Q5KjuPvIk+t8lMKmzAZPn6Kfnuf/l9er6odBr+C8zHeGe7HEYhDyG+++9j/VSOgk65fbwaO4Ds6Tzz2eEBNsRb5pp20mx4Pj/0EmZ3NY0WjloAznbTSmQtFrz4IPG82aHhGu6luuFTsiJ+lcBjzlLaZTWoV50WNmUNPYs5phHJbh1ohAK+4xPRZre76ubbxUUoTPSbbNreFGHln0/6hsnzVRL+X0yZl6gOmzjpzTYIm7dJz4niPEIq/KNw8uFHbmEJNJsQzujy2tad9ah7skwDlDoCiBA62yw+azceR56nZf9I/5AHqCJr4Yti3OoTlAiRv7TmukknymKtNAqc+MlfrTsvsrE0qpTPtVKU5MGpeDdbfPz3vYTqWQIhgwtfEW7dcGxNptiwD04oUSNtQO1hrujCyv40Q7AN8Z1yZwjH7PehCiGm+IuV3Nk6Cx5JggYYFchw+vlbJJwKNtNoRk4oIxQ6SojzKViIvap4="
