sudo: false
dist: trusty

language: c

env:
  global:
    - ARTIFACTS_BUCKET=omniti-mistify-travis-artifacts
    - secure: "Pyds2riYg/c1ilKfq6iuDoJhazFBILavx9/Ldq3opDtmcrBw6CcOJh6XOZ3mH7U9E0JRUnLGIhML/Wlg30/4rmQxtoZjy3cIGa6CUsMjAUGj3WOtxhc4WQ+r461XecF/eIHS5m1ls7O7fEqgasEmUTIOID3c3sUvhOyfMioMQprolzrzPStIfYZgUEpraVmYvq57zjaonsCL1v9piQc484Mq2hIx27wE5xoL+G6PQY08KTiCOLC6ympkQHlFBkIwbcJFk2QRiMpV/XgZVkw8z2/6cBsnATRtPcm1KItuBpULZfz05XN8Y7cYyYiBXea09eU8Tzm2lXT3yHWWdMVcl9zZqQ5R/NCEwx6+V7Eqn8Wi5cqR4SjVZodWJyNBBSHDTpYH+tUtTe4hBBGQ3Db4pwUDCpKgvkdg1XYHVJQ+svUK//zwNMfSgwGBwZ8o4sFQJENQyR94Q6LS76+ot372Bz/Iy9mb1CnhYau8mq14AsB4gkemvm5MS7jMTVEYtU6ayIkPJ7V3Amw9b6Rk/RHRQWrDh0zZlNC9415VUkHfRRBvsiukBDCWm4FUNnP6j4KiqRjbUntmCjY3K5J5Eku/RcnlQZ7wO2C0z8W1jFeOJB21YF92oNLRfN4GzOYD1f531mfidWApz8Nz5r/taPxFciAYzIB0WLbK7kl5nhkWC6A="
    - secure: "J7o949BAeR2cmJ2pO47GsK1QOc7b32krhoAz55KPK7oeo1UKkvCxrOCDuXYYmPFRrgk1KmcYJfRz6+RV56PELRjTR6zHrTEFuHItM+enR39z1CBluwLud4o1kvXfqibQiHogOhhQPQPW5DcyykzbiQ5XcIR00/4TiBklv9zQ42vTjyU+EOPEjPW3mTgp4AuNlOa3kNvoNFNC9PUBKqoeuKePgWhkVdTpZ02e3fcDJ/HkIoKcD9y8JL02WsUET41Vj7fOnnDn1qw4+erthNC3lCreui6sqG14Mk1Lx+9srjODRDJ5j/Rmix49u8um8tsmR6FB/8OFW79ZnEMqasBTZ0AYNcDUQaQk7701mHY0QZ/oZp1eDGPwwY6lGbEasTQkKbTR8m9ETeobeg9uqpn9zKc0TvAOHRH8BUdGg1x87P3K1d0oE2LOTQucHM4TLk7LqVI2iuRPpyotdEqdGZ+6b1e6L3+9ysEQ6dAKHpcS94jjhfFzsiFoFEXSJOGSNx0tgwqCksTNjCroYUEO8f4gRbJ1HMmiqHLRcJKveYlhI1Pa5FxdbRk0Q1uGPPBmog5XgMdE43dxaiQXVCVHXUCR3YdZv+sJoWOmEHzNYL+1AjNNddcYbvV8ssfMpoAB26KBp30JIbZjhF4zgeKADHzEiONci88FM3pSje+YgCjIecY="

addons:
  apt:
    packages:
      - autoconf
      - bc
      - bison
      - flex
      - g++
      - gawk
      - gcc
      - gcc-multilib
      - git
      - gperf
      - libtool
      - make
      - mercurial
      - ncurses-dev
      - openssh-server
      - pv
      - subversion
      - texinfo
      - unzip
      - xz-utils
  artifacts:
    paths:
      - build/mistify/base/logs/build-${TRAVIS_BUILD_ID}.txt


cache:
  ccache: true
  directories:
    - $HOME/.buildroot-ccache
    - $HOME/downloads
    - $HOME/go

install:
  - i=0; while true; do echo "still downloading -- $((i++ * 5)) minutes in"; sleep 300; done &
  - pid=$!
  - ./buildmistify --useartifacts --downloaddir $HOME/downloads --downloadonly --logfile build-${TRAVIS_BUILD_ID}.txt  -- VERBOSE=0 -s
  - kill $pid

script:
  - i=0; while true; do echo "still building -- $((i++ * 5)) minutes in"; sleep 300; done &
  - pid=$!
  - ./buildmistify --useartifacts --downloaddir $HOME/downloads --godir $HOME/go --logfile build-${TRAVIS_BUILD_ID}.txt |& grep '>>>'
  - kill $pid
  - echo 'last 1000 lines of log file'
  - tail -1000 build/mistify/base/logs/build-${TRAVIS_BUILD_ID}.txt

notifications:
  email: false
  slack:
    secure: "U6tm6D5myVwg3FL+zeWpfW17GrM8pVOayDYIvuagawGhKu/zftHxqwD9GQP54P1YvHSxGs0g2i7ZT4EM+EOLiHewG80Dk5Ndzrxr8Ck5mjFCxJDQkW45QaQBvY13+u9CY4i/g8LyAIOvoSxYAQS9n2dWTCgkXuSwnjUcDkaeY/Owk1qVBvu+ZeoCY02MRwUJsM5f1Q5KjuPvIk+t8lMKmzAZPn6Kfnuf/l9er6odBr+C8zHeGe7HEYhDyG+++9j/VSOgk65fbwaO4Ds6Tzz2eEBNsRb5pp20mx4Pj/0EmZ3NY0WjloAznbTSmQtFrz4IPG82aHhGu6luuFTsiJ+lcBjzlLaZTWoV50WNmUNPYs5phHJbh1ohAK+4xPRZre76ubbxUUoTPSbbNreFGHln0/6hsnzVRL+X0yZl6gOmzjpzTYIm7dJz4niPEIq/KNw8uFHbmEJNJsQzujy2tad9ah7skwDlDoCiBA62yw+azceR56nZf9I/5AHqCJr4Yti3OoTlAiRv7TmukknymKtNAqc+MlfrTsvsrE0qpTPtVKU5MGpeDdbfPz3vYTqWQIhgwtfEW7dcGxNptiwD04oUSNtQO1hrujCyv40Q7AN8Z1yZwjH7PehCiGm+IuV3Nk6Cx5JggYYFchw+vlbJJwKNtNoRk4oIxQ6SojzKViIvap4="
