#!/bin/bash
#+
# Use this script to trigger a build on a Jenkins server for the working branch.
#-

jenkinsdefault=http://mistify-dev-2.office.omniti.com:8081
mistifybranch=`git status | grep "On branch" | cut -f 3 -d ' '`

usage () {
    cat << EOF
Usage: ./jenkins [options] [target]
  Use this script to remotely trigger a Mistify build on a Jenkins CI server. 
  The Jenkins CI server must be configured to run the buildmistify script on the
  server in order to build.
  Options:
    ==== remote build ====
    --jenkins <URL>
        The Jenkins CI server URL. The URL is saved in the file 
        $statedir/jenkins.
        [jenkins=`cat $statedir/jenkins`]
        Parameters passed to the Jenkins server:
        [branch=$mistifybranch]
    ==== other ====
    --test
        Just testing what will happen with this script. Don't run the Buildroot
        make.
    -h|--help
        Display this usage.

  NOTE: This script maintains state in $statedir.
EOF
}

source scripts/mistify-functions.sh

#+
# Handle the command line options.
#-
a=`getopt -l "\
jenkins:,\
test,\
help" \
   -o "h" -- "$@"`

if [ $? -gt 0 ]; then
    usage
    exit 1
fi

eval set -- $a

while [ $# -ge 1 ]; do
    case "$1" in
	--)
	    shift
	    break
	    ;;
	--jenkins)
	    jenkins=$2
	    shift
	    ;;
	--test)
	    testing=y
	    ;;
	-h|--help)
	    usage
	    exit 0
	    ;;
	# using getopt should avoid needing this catchall but just in case...
	*)
	    error "Invalid option: $1"
	    usage
	    exit 1
	    ;;
    esac
    shift
done

if [ -z "$jenkins" ]; then
    if [ -f $statedir/jenkins ]; then
	jenkins=`cat $statedir/jenkins`
    else
	jenkins=$jenkinsdefault
    fi
fi
echo $jenkins >$statedir/jenkins

jenkinscommand="wget -O /dev/null $jenkins/job/MistifyOS-remote/buildWithParameters?token=buildmistify&branch=$mistifybranch"

if [ -n "$testing" ]; then
  message "Just a test run -- not building."
  verbose $jenkinscommand
  exit 0
fi

message "Triggering a remote build on Jenkins server: $jenkins"
message "The branch is: $mistifybranch"
$jenkinscommand
if [ $? -gt 0 ]; then
  error The Jenkins server is not running at the URL or did not accept the job.
  exit 1
fi
