#!/bin/sh

source /etc/pre-init.d/net-init.sh

if [ x$new_domain_name_servers != x ]
then
  echo "DNS=($new_domain_name_servers)" >> $MISTIFY_IFSTATE
fi

if [ x$new_dhcp_server_identifier != x ]
then
  echo SERVER=$new_dhcp_server_identifier >> $MISTIFY_IFSTATE
fi
