#!/usr/bin/env bash

set -e

function out() {
	tee /proc/self/fd/3 | systemd-cat -t cluster-init-out
}
function err() {
	tee /proc/self/fd/3 | systemd-cat -t cluster-init-err
}

exec 3>&2
exec 1> >(out)
exec 2> >(err)

function do_until() {
	local t=$1
	local cmd=$2
	shift 2
	local i=0
	until $cmd "$@"; do
		sleep $t
		echo "$((++i * $t))s elapsed"
	done
}

source $(dirname $0)/cluster-init-config

ip=${ips[0]}

echo "$LINENO: stopping nconfigd to avoid races"
systemctl stop nconfigd
echo "$LINENO: done"

echo "$LINENO: setting up etcd keys"
etcdctl set /lochness/hypervisors/${uuids[0]}/config/dhcpd true
etcdctl set /lochness/hypervisors/${uuids[0]}/config/dns true
etcdctl set /lochness/hypervisors/${uuids[0]}/config/cbootstrapd true
etcdctl set /lochness/hypervisors/${uuids[0]}/config/etcd true
etcdctl set /lochness/hypervisors/${uuids[0]}/config/tftpd true

etcdctl set /lochness/hypervisors/${uuids[1]}/config/dns true
etcdctl set /lochness/hypervisors/${uuids[1]}/config/etcd true
etcdctl set /lochness/hypervisors/${uuids[2]}/config/dns true
etcdctl set /lochness/hypervisors/${uuids[2]}/config/etcd true
echo "$LINENO: done"

echo "$LINENO: setting up network"
rm -f /etc/systemd/network/*
cat > /etc/systemd/network/br0.netdev <<EOF
[NetDev]
Name=br0
Kind=bridge
EOF

cat > /etc/systemd/network/br0.network <<EOF
[Match]
Name=br0

[Network]
DNS=127.0.0.1
Address=$ip/$nm
Gateway=$gw
EOF

cat > /etc/systemd/network/ethernet.network <<EOF
[Match]
Name=en*

[Network]
Bridge=br0
EOF

cat > /etc/resolv.conf <<EOF
nameserver 127.0.0.1
EOF

systemctl restart systemd-networkd
echo "$LINENO: done"


echo "$LINENO: waiting for nconfigd/ansible"
nconfigd --once && systemctl stop nconfigd
dig +short dns.services.lochness.local @127.0.0.1 -p 15353 || echo "$LINENO: ok well that failed, but lets continue anyway"
echo "$LINENO: done"

echo "$LINENO: setting up etcd to listen on external interfaces"
cat > /etc/sysconfig/etcd <<EOF
ETCD_LISTEN_CLIENT_URLS=http://$ip:2379,http://$ip:4001,http://localhost:2379,http://localhost:4001
EOF
systemctl restart etcd
sleep .100
echo "$LINENO: done"

echo "$LINENO: waiting for etcd to come back fully"
do_until 1 etcdctl cluster-health
echo "$LINENO: done"

echo "$LINENO: setting up other nodes in etcd"
stop=$((${#uuids[*]} - 1))
for i in $(seq 0 $stop); do
	echo "${uuids[$i]}"
	etcdctl set /lochness/hypervisors/${uuids[$i]}/config/etcd true
	cat <<-EOF | tr -d '\n' | etcdctl set /lochness/hypervisors/${uuids[$i]}/metadata
	{"id":"${uuids[$i]}","ip":"${ips[$i]}","netmask":"255.255.255.0","gateway":"$gw","mac":"${macs[$i]}"}
	EOF
	cat <<-EOF | tr -d '\n' | etcdctl set /queensland/nodes/${uuids[$i]}
	{"ip":"${ips[$i]}"}
	EOF
	cat <<-EOF | tr -d '\n' | etcdctl set /queensland/services/etcd-server/${uuids[$i]}
	{"priority":0,"weight":0,"port":2380,"target":"${uuids[$i]}"}
	EOF
done
echo "$LINENO: done"

echo "$LINENO: waiting for nconfigd to process new nodes, then stopping nconfigd"
nconfigd --once && systemctl stop nconfigd
echo "$LINENO: done"

echo "$LINENO: waiting for etcd to come back fully"
do_until 1 etcdctl cluster-health
echo "$LINENO: done"

echo "$LINENO: setting up etcd cluster"
etcdctl set /lochness/config/ETCD_DISCOVERY_SRV 'services.lochness.local'
etcdctl set /lochness/config/ETCD_INITIAL_CLUSTER_STATE 'new'
etcdctl set /lochness/config/ETCD_INITIAL_CLUSTER_TOKEN 'etcd-cluster-1'
for i in $(seq 0 $stop)
do
	path="/lochness/hypervisors/${uuids[$i]}/config"
	echo "$path"
	etcdctl set $path/NCONFIGD_ETCD_ADDRESS http://$ip:4001
	etcdctl set $path/ETCD_ADVERTISE_CLIENT_URLS "http://${uuids[$i]}.nodes.lochness.local:2379,http://${uuids[$i]}.nodes.lochness.local:4001"
	etcdctl set $path/ETCD_INITIAL_ADVERTISE_PEER_URLS "http://${uuids[$i]}.nodes.lochness.local:2380"
	etcdctl set $path/ETCD_LISTEN_CLIENT_URLS "http://${uuids[$i]}.nodes.lochness.local:2379,http://${uuids[$i]}.nodes.lochness.local:4001,http://localhost:2379,http://localhost:4001"
	etcdctl set $path/ETCD_LISTEN_PEER_URLS "http://${uuids[$i]}.nodes.lochness.local:2380"
	etcdctl set $path/ETCD_NAME "${uuids[$i]}"
done
echo "$LINENO: done"

echo "$LINENO: checking for kernel/initrd existence"
do_until 5 ls -l /var/lib/images/0.1.0/{vmlinuz,initrd}
echo "$LINENO: done"

echo "$LINENO: ok you can now boot node1 and node2"
do_until 5 curl --silent http://${ips[1]}:4001/v2/keys
do_until 5 curl --silent http://${ips[2]}:4001/v2/keys
echo "$LINENO: ok new etcd cluster seems to be up"

echo "$LINENO: sleeping 2m to let new nodes settle"
sleep 2m
echo "$LINENO: done"

echo "$LINENO: syncing queensland data from old cluster to new"
etcdctl ls --recursive --sort -p /queensland | sed '/\/$/ d' | while read key; do
	etcdctl get $key | sed 's|^|value=|' | curl -s -XPUT http://${ips[1]}:4001/v2/keys$key -d@-
done
echo "$LINENO: done"

echo "$LINENO: setting hv1 to be dns server (temporarily)"
curl -s -XPUT http://${ips[1]}:4001/v2/keys/lochness/hypervisors/${uuids[1]}/config/dns -dvalue=true
echo "$LINENO: done"

echo "$LINENO: backing up etcd data"
etcdctl ls --sort --recursive -p | sed '/\/$/ d' | while read key; do
	printf "%s %s\n" "$(printf $key | base64 -w0)" "$(base64 -w0 <(etcdctl get $key))"
done > /tmp/etcd.dump
echo "$LINENO: done"

echo "$LINENO: waiting for other dns server to come up"
do_until 5 dig +short dns.services.lochness.local @${ips[1]}
echo "done"

echo "$LINENO: restarting etcd so it can join the cluster"
cat /dev/null > /etc/sysconfig/etcd
curl -s http://localhost:8888/config/$ip > /tmp/mistify-config
cat > /etc/resolv.conf <<EOF
nameserver ${ips[1]}
nameserver ${ips[2]}
nameserver ${ips[0]}
EOF
systemctl stop etcd confd named dhcpd cbootstrapd tftpd
rm -rf /mistify/data/etcd/*
systemctl start etcd
echo "$LINENO: done"

echo "$LINENO: waiting for etcd cluster to be healthy"
do_until 5 etcdctl cluster-health
echo "$LINENO: done"

echo "$LINENO: restoring etcd data"
while read key value; do
	echo $value | base64 -d | sed 's|^|value=|' | \
		curl -s -XPUT "http://localhost:4001/v2/keys$(echo $key | base64 -d)" -d@-
done < /tmp/etcd.dump
echo "$LINENO: done"

echo "$LINENO: restarting nconfigd so it can do its thing"
nconfigd --once
echo "$LINENO: done"

echo "$LINENO: updating resolv.conf nameserver order"
cat > /etc/resolv.conf <<EOF
nameserver ${ips[0]}
nameserver ${ips[1]}
nameserver ${ips[2]}
EOF
echo "$LINENO: done"
