---

- queensland: service=dns
  register: dhcpd_nameservers

- file: path=/etc/dhcpd state=directory owner=root mode=0755

- template: src=dhcpd.conf.j2 dest=/etc/dhcpd/dhcpd.conf owner=root mode=0644
  notify: dhcpd-restart

- file: path=/etc/dhcpd/hypervisors.conf state=touch

- file: path=/etc/dhcpd/guests.conf state=touch

- template: src=dhcpd.service.j2 dest=/etc/systemd/system/dhcpd.service owner=root mode=0644
  notify: systemd-reload
  notify: dhcpd-restart

- template: src=dhcpd-announce.service.j2 dest=/etc/systemd/system/dhcpd-announce.service owner=root mode=0644
  notify: systemd-reload
  notify: dhcpd-announce-restart

- template: src=hypervisors.conf.tmpl.j2 dest=/etc/confd/templates/hypervisors.conf.tmpl owner=root mode=0644
  notify: confd-restart

- template: src=hypervisors.toml.j2 dest=/etc/confd/conf.d/hypervisors.toml owner=root mode=0644
  notify: confd-restart

- template: src=guests.conf.tmpl.j2 dest=/etc/confd/templates/guests.conf.tmpl owner=root mode=0644
  notify: confd-restart

- template: src=guests.toml.j2 dest=/etc/confd/conf.d/guests.toml owner=root mode=0644
  notify: confd-restart

- service: name=dhcpd.service state=started enabled=yes

- service: name=dhcpd-announce.service state=started enabled=yes
