---

# we need to discover the nodes running DNS so that we can
# populate the dhcpd config. Currently, just using an ansible variable
# but we may want a simple module for such discoveries

- file: path=/etc/dhcpd state=directory owner=root mode=0755

- include: enable.yml
  when: dhcpd_enable

- include: disable.yml
  when: not dhcpd_enable
