---
- template: src=cherufe.service.j2 dest=/etc/systemd/system/cherufe.service owner=root mode=0644
  notify:
    - systemd-reload
    - cherufe-restart

- service: name=cherufe state=started enabled=yes
