#!/bin/sh


# Stop all init scripts in /etc/init.d
#
for i in $(ls /etc/init.d/K??*) ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i stop
	    ;;
    esac

/etc/init.d/RChalt stop

done

