#!/bin/bash
set -e

. /lib/lsb/init-functions

declare -a OVERLAYS=(
    etc
    var
    root
    home
)

# Create AUFS overlay mountpoints under /mistify/private
mount_aufs () {
	for D in ${OVERLAYS[@]}; do
		[ -d /mistify/private/$D ] || mkdir /mistify/private/$D
		log_action_msg "Mounting AUFS filesystem /$D"
		mount -t aufs -o br:/mistify/private/$D:/$D=ro none $D
	done
}

# Unmount AUFS filesystems
umount_aufs () {
	for D in ${OVERLAYS[@]}; do
		log_action_msg "Unmounting AUFS filesystem /$D"
		umount /$D
	done
}

case "$1" in
	start)
		mount_aufs
	;;

	stop)
		umount_aufs
	;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0
