#!/bin/bash
set -e

declare -a OVERLAYS=(
    /etc
    /var
    /root
    /home
)

# Create AUFS overlay mountpoints under /mistify/private
for D in ${OVERLAYS[@]}; do
    [ -d /mistify/private$D ] || mkdir /mistify/private$D
    mount -t aufs -o br:/mistify/private$D:$D=ro none $D
done

# permissions
chmod 0775 /mistify/private/var/log
