#!/bin/bash
##
## This script is a pre-requisite to confd.service
##
## It ensures that the data directory and basic configuration is in place
## under the mistify zpool so that confd runs on first boot.
##

# Read in confd runtime options
if [ -f /etc/sysconfig/confd ]; then
	. /etc/sysconfig/confd
else
	exit 1
fi

function confd_setup {

	# Create confd's confdir if it does not exist
	if [ -d /mistify/data -a ! -d $CONF_DIR ]; then
		mkdir -p $CONF_DIR
	fi

	# Create confd's template and conf directories
	if [ ! -d $CONF_DIR/templates ]; then
		mkdir -p $CONF_DIR/templates
	fi
	if [ ! -d $CONF_DIR/conf.d ]; then
		mkdir -p $CONF_DIR/conf.d
	fi

	# Ensure the data_dir has the correct ownership
	CONF_DIR_OWNER=`stat -c "%U %G" $CONF_DIR`
	if [ "$CONF_DIR_OWNER" != "confd daemon" ]; then
		chown -R confd $DATA_DIR
		chgrp -R daemon $DATA_DIR
	fi
}

confd_setup

exit 0
