#!/bin/bash


# This script runs following a build of the target file system, $(TARGET_DIR).
#
# NOTE: In order for this script to execute the defconfig must point to it.
# For more information see: 
#   http://buildroot.uclibc.org/downloads/manual/manual.html#rootfs-custom
# TODO: Maybe move the lists to a config file?
#-

targetdir=$1

#
# Install a symlink for /sbin/getty that points to /sbin/agetty.
# A lot of things expect /sbin/getty to be present.
#
if [ ! -f $targetdir/sbin/getty ]; then
  if [ -x $targetdir/sbin/agetty ]; then
    (cd $targetdir/sbin && ln -s agetty getty)
  fi
fi

#
# Ensure /var/lock/subsys exists
#
if [ ! -d $targetdir/var/lock/subsys ]; then
  mkdir -p $targetdir/var/lock/subsys
fi

#
# Ensure /var/tmp is a directory and not a symlink
#
if [ ! -d $targetdir/var/tmp ]; then
  rm -f $targetdir/var/tmp
  mkdir -p $targetdir/var/tmp
fi

#
# Ensure /run is a directory and not a symlink
#
if [ ! -d $targetdir/run ]; then
  rm -f $targetdir/run
  mkdir -p $targetdir/run
fi

#
# Clean out the /src directory
#
if [ -d $targetdir/src ]; then
  rm -rf $targetdir/src
fi
