#!/bin/bash


# This script runs following a build of the target file system, $(TARGET_DIR).
#
# NOTE: In order for this script to execute the defconfig must point to it.
# For more information see: 
#   http://buildroot.uclibc.org/downloads/manual/manual.html#rootfs-custom
# TODO: Maybe move the lists to a config file?
#-

targetdir=$1

#
# Install a symlink for /sbin/getty that points to /sbin/agetty.
# A lot of things expect /sbin/getty to be present.
#
if [ ! -f $targetdir/sbin/getty ]; then
  if [ -x $targetdir/sbin/agetty ]; then
    (cd $targetdir/sbin && ln -s agetty getty)
  fi
fi

#
# Remove /etc/init.d
#
if [ -d $targetdir/etc/init.d ]; then
  rm -rf $targetdir/etc/init.d
fi

#
# Clean out the /src directory
#
if [ -d $targetdir/src ]; then
  rm -rf $targetdir/src
fi

#
# Create a missing symlink for the UTC timezone
#
ln -sf Etc/UTC $targetdir/usr/share/zoneinfo/UTC
