#!/bin/sh
exec 2>&1
[ -f /etc/ssh/ssh_host_dsa_key ] || ssh-keygen -t dsa -N "" -f /etc/ssh/ssh_host_dsa_key
[ -f /etc/ssh/ssh_host_rsa_key ] || ssh-keygen -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
[ -f /etc/ssh/ssh_host_ecdsa_key ] || ssh-keygen -t ecdsa -N "" -f /etc/ssh/ssh_host_ecdsa_key

chmod 700 /etc/ssh/*_key

exec /usr/sbin/sshd -f /etc/ssh/sshd_config -D 2>&1
